# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."csb14_postgres" = {
    image = "postgres";
    environment = {
      "POSTGRES_PASSWORD" = "postgres";
      "POSTGRES_USER" = "postgres";
    };
    volumes = [
      "csb14_postgres_postgres:/data/csb14_postgres:rw"
    ];
    ports = [
      "5432:5432/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=csb14_postgres"
      "--network=csb14_postgres_default"
    ];
  };
  systemd.services."docker-csb14_postgres" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-csb14_postgres_default.service"
      "docker-volume-csb14_postgres_postgres.service"
    ];
    requires = [
      "docker-network-csb14_postgres_default.service"
      "docker-volume-csb14_postgres_postgres.service"
    ];
    partOf = [
      "docker-compose-csb14_postgres-root.target"
    ];
    wantedBy = [
      "docker-compose-csb14_postgres-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-csb14_postgres_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f csb14_postgres_default";
    };
    script = ''
      docker network inspect csb14_postgres_default || docker network create csb14_postgres_default
    '';
    partOf = [ "docker-compose-csb14_postgres-root.target" ];
    wantedBy = [ "docker-compose-csb14_postgres-root.target" ];
  };

  # Volumes
  systemd.services."docker-volume-csb14_postgres_postgres" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect csb14_postgres_postgres || docker volume create csb14_postgres_postgres
    '';
    partOf = [ "docker-compose-csb14_postgres-root.target" ];
    wantedBy = [ "docker-compose-csb14_postgres-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-csb14_postgres-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
