# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."orcldb-db" = {
    image = "container-registry.oracle.com/database/free:latest";
    environment = {
      "ORACLE_PWD" = "oracle";
    };
    volumes = [
      "/home/jakob/.nix/modules/docker/orcldb/setup-scripts:/opt/oracle/scripts/setup:rw"
    ];
    ports = [
      "1521:1521/tcp"
      "5500:5500/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=db"
      "--network=orcldb_default"
    ];
  };
  systemd.services."docker-orcldb-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-orcldb_default.service"
    ];
    requires = [
      "docker-network-orcldb_default.service"
    ];
    partOf = [
      "docker-compose-orcldb-root.target"
    ];
    wantedBy = [
      "docker-compose-orcldb-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-orcldb_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f orcldb_default";
    };
    script = ''
      docker network inspect orcldb_default || docker network create orcldb_default
    '';
    partOf = [ "docker-compose-orcldb-root.target" ];
    wantedBy = [ "docker-compose-orcldb-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-orcldb-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
