services:
  csb124_postgres:
    container_name: csb124_postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
       - csb124_postgres:/data/csb124_postgres
    ports:
      - "5432:5432"
    # networks:
    #   - csb124_postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    # networks:
    #   - csb124_postgres
    restart: unless-stopped
  
# networks:
#   csb124_postgres:
#     driver: bridge
#
volumes:
    csb124_postgres:
    pgadmin:
