# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."csb124_postgres" = {
    image = "postgres";
    environment = {
      "POSTGRES_PASSWORD" = "postgres";
      "POSTGRES_USER" = "postgres";
    };
    volumes = [
      "csb124_postgres_csb124_postgres:/data/csb124_postgres:rw"
    ];
    ports = [
      "5432:5432/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=csb124_postgres"
      "--network=csb124_postgres_default"
    ];
  };
  systemd.services."docker-csb124_postgres" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-csb124_postgres_default.service"
      "docker-volume-csb124_postgres_csb124_postgres.service"
    ];
    requires = [
      "docker-network-csb124_postgres_default.service"
      "docker-volume-csb124_postgres_csb124_postgres.service"
    ];
    partOf = [
      "docker-compose-csb124_postgres-root.target"
    ];
    wantedBy = [
      "docker-compose-csb124_postgres-root.target"
    ];
  };
  virtualisation.oci-containers.containers."pgadmin_container" = {
    image = "dpage/pgadmin4";
    environment = {
      "PGADMIN_CONFIG_SERVER_MODE" = "False";
      "PGADMIN_DEFAULT_EMAIL" = "pgadmin4@pgadmin.org";
      "PGADMIN_DEFAULT_PASSWORD" = "admin";
    };
    volumes = [
      "csb124_postgres_pgadmin:/var/lib/pgadmin:rw"
    ];
    ports = [
      "5050:80/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=pgadmin"
      "--network=csb124_postgres_default"
    ];
  };
  systemd.services."docker-pgadmin_container" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-csb124_postgres_default.service"
      "docker-volume-csb124_postgres_pgadmin.service"
    ];
    requires = [
      "docker-network-csb124_postgres_default.service"
      "docker-volume-csb124_postgres_pgadmin.service"
    ];
    partOf = [
      "docker-compose-csb124_postgres-root.target"
    ];
    wantedBy = [
      "docker-compose-csb124_postgres-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-csb124_postgres_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f csb124_postgres_default";
    };
    script = ''
      docker network inspect csb124_postgres_default || docker network create csb124_postgres_default
    '';
    partOf = [ "docker-compose-csb124_postgres-root.target" ];
    wantedBy = [ "docker-compose-csb124_postgres-root.target" ];
  };

  # Volumes
  systemd.services."docker-volume-csb124_postgres_csb124_postgres" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect csb124_postgres_csb124_postgres || docker volume create csb124_postgres_csb124_postgres
    '';
    partOf = [ "docker-compose-csb124_postgres-root.target" ];
    wantedBy = [ "docker-compose-csb124_postgres-root.target" ];
  };
  systemd.services."docker-volume-csb124_postgres_pgadmin" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect csb124_postgres_pgadmin || docker volume create csb124_postgres_pgadmin
    '';
    partOf = [ "docker-compose-csb124_postgres-root.target" ];
    wantedBy = [ "docker-compose-csb124_postgres-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-csb124_postgres-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
