services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "mssql"
    ports:
      - 1433:1433
    volumes:
      - my-volume:/var/opt/mssql
      
volumes:
  my-volume:
