# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."mssql-sqldata" = {
    image = "mcr.microsoft.com/mssql/server:2017-latest";
    environment = {
      "ACCEPT_EULA" = "Y";
      "SA_PASSWORD" = "mssql";
    };
    ports = [
      "1433:1433/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=sqldata"
      "--network=mssql_default"
    ];
  };
  systemd.services."docker-mssql-sqldata" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-mssql_default.service"
    ];
    requires = [
      "docker-network-mssql_default.service"
    ];
    partOf = [
      "docker-compose-mssql-root.target"
    ];
    wantedBy = [
      "docker-compose-mssql-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-mssql_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f mssql_default";
    };
    script = ''
      docker network inspect mssql_default || docker network create mssql_default
    '';
    partOf = [ "docker-compose-mssql-root.target" ];
    wantedBy = [ "docker-compose-mssql-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-mssql-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
